version: "3.9"

services:
  jobboard-db:
    container_name: jobboard
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=jobboard
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
  
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
