job-service-url: http://job:8081
company-service-url: http://company:8082
review-service-url: http://review:8083

server:
  port: 8081

spring:
  application:
    name: company-service
  datasource:
    url: jdbc:postgresql://postgres:5432/jobboard
    username: admin
    password: admin123
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  #RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://servicereg:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  #Zipkin
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0



