job-service-url: http://job:8081
company-service-url: http://company:8082
review-service-url: http://review:8083

server:
  port: 8081

spring:
  application:
    name: company-service
  config:
    import: configserver:http://configserver:8084
  profiles:
    active: default






