job-service-url: http://localhost:8081
company-service-url: http://localhost:8082
review-service-url: http://localhost:8083

server:
  port: 8081

spring:
  application:
    name: company-service
  config:
    import: config-server:http://localhost:8084
  profiles:
    active: default



