pipeline {

    environment {
        DOCKER_IMAGE_NAME = "guilhermeozana/jobboard-company"
        DOCKER_IMAGE = ""

    }

    agent any

    stages {

        stage('Checkout Source') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: 'main']], userRemoteConfigs: [[url: 'https://github.com/guilhermeozana/jobboard-backend.git']]])
            }
        }

        stage ('Build Companyms JAR') {
            steps {
                dir("shared") {
                    bat 'mvn clean install -DskipTests=true'
                }

                dir("companyms") {
                    bat 'mvn clean install -DskipTests=true'
                    bat 'mvn package -DskipTests=true'
                }   
            }
        }
    
        stage('Build Docker Image') {
            steps {
                script {
                    dir("companyms") {
                        bat "docker build -t ${DOCKER_IMAGE_NAME} ."
                        
                        bat "docker tag ${DOCKER_IMAGE_NAME} ${DOCKER_IMAGE_NAME}:${env.BUILD_NUMBER}"
                        
                        bat "docker tag ${DOCKER_IMAGE_NAME} ${DOCKER_IMAGE_NAME}:latest"
                    }
                }
            }
        }

        stage('Push Docker Image') {
            environment {
                registryCredential = "dockerhublogin"
            }

            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', registryCredential) {
                        dockerImage.push("${DOCKER_IMAGE_NAME}:${env.BUILD_NUMBER}")
                        dockerImage.push("${DOCKER_IMAGE_NAME}:latest")
                    }
                }
            }
        }

        stage('Deploy to Kubernetes') {

            steps {
                script {
                    kubernetesDeploy(configs: "kubernetes/bootstrap/company/company-deployment.yml", kubeconfigId: "kubernetes")
                }
            }
        }
    }
}