pipeline {

    environment {
        DOCKER_IMAGE_NAME = "guilhermeozana/jobboard-company"
        DOCKER_IMAGE = ""

    }

    agent any

    stages {

        stage('Checkout Source') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: 'main']], userRemoteConfigs: [[url: 'https://github.com/guilhermeozana/jobboard-backend.git']]])
            }
        }

        stage ('Build Companyms') {
            steps {
                dir("companyms") {
                    bat 'mvn clean package -DskipTests=true'
                }   
            }
        }
    
        stage('Build image') {
            steps {
                script {
                    dir("companyms") {
                        DOCKER_IMAGE = docker.build("${DOCKER_IMAGE_NAME}")
                        docker.tag(DOCKER_IMAGE.id, "${DOCKER_IMAGE_NAME}:${env.BUILD_NUMBER}")
                        docker.tag(DOCKER_IMAGE.id, "${DOCKER_IMAGE_NAME}:latest")
                    }
                }
            }
        }

        stage('Push Image') {
            environment {
                registryCredential = "dockerhublogin"
            }

            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', registryCredential) {
                        dockerImage.push("${DOCKER_IMAGE_NAME}:${env.BUILD_NUMBER}")
                        dockerImage.push("${DOCKER_IMAGE_NAME}:latest")
                    }
                }
            }
        }

        stage('Deploy to Kubernetes') {

            steps {
                script {
                    kubernetesDeploy(configs: "kubernetes/bootstrap/company/company-deployment.yml", kubeconfigId: "kubernetes")
                }
            }
        }
    }
}